### PR TITLE
Fix feedback form button color

### PR DESCRIPTION
**Pull request by thecodepapaya**
Randomly changing button color
---
videotogif_2019 09 02_02 10 27

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Don't make it random, fix one style for dark and one for light mode.

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Check comments

**Comment by thecodepapaya** [comment]
videotogif_2019 09 03_19 46 36

**Review by aashutoshrathi — APPROVED** [review]
LGTM

**Pull request merged**
