### PR TITLE
Add google sign in

### PR DESCRIPTION
**Pull request by thecodepapaya**
Add google sign in for #6 
___
videotogif_2019 08 25_16 41 21

### CODE REVIEW

**Review by aashutoshrathi — COMMENTED** [review]
Save the shared preferences.

**Comment by thecodepapaya** [comment]
Name and email address are automatically saved for each user upon signing in with google and then the same are used to identify users in their feedback.

**Review by aashutoshrathi — APPROVED** [review]
LGTM, also add a QR on the screen resolving to be user's email

**Comment by thecodepapaya** [comment]
Implemented google sign in page as designed by @pranayag sir

videotogif_2019 09 05_01 03 09

**Review by aashutoshrathi — APPROVED** [review]
This looks great. Update the references in DB as per new DB

**Pull request merged**
