### PR TITLE
Add firebase connectivity 

### PR DESCRIPTION
**Pull request by thecodepapaya**
Show mock data from Firebase for Sponsors, Team and Speakers Page

### CODE REVIEW

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
`android/app/google-services.json` shouldn't be checked to git, right?

**Comment by aashutoshrathi** [comment]
@ashutoshsingh05 Please add a GIF for ease of review.

**Comment by ashutoshsingh05** [comment]
|---|---|

**Comment by ashutoshsingh05** [comment]
|Type|Gif|
|---|---|
|Agenda Page|---|
|Agenda Page|---|

**Comment by thecodepapaya** [comment]
|Page|Fetched from Firebase(New)|Hard Coded(Old)|
|---|---|---|
|Agenda Page|agenda|agenda-old|
|Speakers Page|speakers|speakers-old|
|Team Page|teams|teams-old|
|Sponsors Page|sponsor|sponsors-old|

**Review by aashutoshrathi — APPROVED** [review]
Yeah, this works well.
Please change the dummy data to real data by consulting @parth181195

**Pull request merged**
